name: Release

concurrency: ci-${{ github.ref }}

on:
  workflow_dispatch:
  push:
    branches: [ main ] # Default release branch
    paths-ignore:
      - '.github/**'
      - 'docs/**'
      - '**/.ts/**'
      - '**/.nx/**'

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  call-workflow-nuget-release:
    uses: Digitalroot-Valheim/.github/.github/workflows/nuget.release.yml@main
    secrets:
      aws-access-key-id: ${{ secrets.NUGET_S3_REPO_KEY_ID }}
      aws-secret-access-key: ${{ secrets.NUGET_S3_REPO_KEY_SECRET }}
      nexus-api-key: ${{ secrets.NEXUS_API_KEY }}
      nexus-cookie-nxid-header: ${{ secrets.NEXUS_COOKIE_HEADER_NEXUSID }}
      nexus-cookie-sid-header: ${{ secrets.NEXUS_COOKIE_HEADER_SID_DEVELOP }}
      ts-api-key: ${{ secrets.TS_SERVICEACCOUNT }}
      
    with:
      sln-file-name: Digitalroot.Valheim.EternalFire
      proj-file-name: Digitalroot.Valheim.EternalFire
      is-nuget-package: false
      nexus-enable-upload: false
      nexus-mod-id: 1463
      ts-enable-upload: false
      ts-name: Eternal_Fire
      ts-description: "Keeps fires burning."
      ts-categories: "server-side client-side tweaks" #https://thunderstore.io/api/experimental/community/valheim/category/
      ts-dependencies: denikson-BepInExPack_Valheim@5.4.2105 ValheimModding-Jotunn@2.11.5
